image: rust:buster

stages:
  - build

before_script:
  - apt-get update -yqq
  - apt-get install -yqq debconf-utils
  - echo "jackd2  jackd/tweak_rt_limits   boolean false" | debconf-set-selections
  - apt-get install -yqq build-essential pkgconf libdbus-1-dev libasound-dev libglib2.0-dev libsdl-pango-dev libatk1.0-dev libgdk-pixbuf2.0-dev libgtk-3-dev libappindicator3-dev libjack-jackd2-dev clang jackd2
  - rustup default stable
  - rustup update


rust-latest:
  stage: build
  script:
    - cargo build